server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://106.14.139.216:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.hmoro.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/