server:
  port: 8080
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # true, 会从Eureka Server服务的列表只读备份，然后缓存在本地，默认为 true
    registry-fetch-interval-seconds: 5 # 每隔 5s 重新获取并更新数据，默认 30s
# 修改Ribbon负载均衡策略 默认是轮询 com.netflix.loadbalancer.RoundRobinRule
# com.netflix.loadbalancer.IRule接口的实现类
# 服务提供方的服务id
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 # 设置 hystrix 的超时时间 ,默认 1000ms，开发环境机器运行速度慢的情况下，可以适当调大一些
feign:
  hystrix:
    enabled: true # 开启 feign 的熔断功能